---
output:
  pdf_document: default
  html_document: default
---

# Introduction

Ecological dynamic models describe how ecological processes drive populations to change over time by estimating the parameters of the deterministic process, observation error, and process error from a single time series [@bolkerEcologicalModelsData2008]. However, estimating parameters for dynamic models is challenging. One simplification is to assume that the dynamic model only has observation error, which can be implemented by starting with the initial conditions of the system and computing the entire trajectory over the domain at once. This approach assumes there is no uncertainty in the predicted values of the states at each time step, meaning there is no process error. Since the trajectory at every time step is determined solely by the starting parameters and initial conditions, the model is deterministic. The only error accounted for is the difference between observed and predicted values.

To fit the model to data and compute the maximum likelihood estimate (MLE) for a given set of parameters, one assumes independent observations and sums the likelihood for each observation based on the chosen model of observation error. Using a quasi-Newton method, parameter estimates are updated based on the current iteration of trajectory matching until convergence is achieved. If the observation error is normally distributed with constant variance, this process simplifies to least squares fitting.

In modeling infectious diseases, for example, one may be interested in estimating the unobserved process of the transmission rate between an infectious individual and a susceptible one. Assuming a fixed value for the transmission rate at every time step is often inaccurate because many diseases have dynamic transmission rates influenced by factors such as seasonality or non-pharmaceutical interventions (e.g., social distancing, masking, and changes in mobility patterns). Therefore, it is reasonable to assume that the transmission rate is a time-varying parameter, computed at each observed data point.

A standard method for dealing with time-varying parameters is to introduce a parametric model and estimate its parameters as part of the MLE process. However, imposing a particular shape on the unknown function describing the unobserved process, is often a phenomenological characterization rather than one derived from known biological mechanisms. This can lead to mismatches between the model and data not due to biological inaccuracies but due to the chosen parametric form of the latent variable.

Fitting dynamic ecological models with time-varying latent variables is a challenging task. Rather than specifying the functional form of the unknown function _a priori_, we can adopt a more flexible function estimation method that minimizes incidental assumptions and model misspecification. [@wahbaSplineModelsObservational1990] and [@hastieGeneralizedAdditiveModels1990] developed methodologies for general non-parametric statistical modeling, which have been applied to ecological modeling. Wood and Nisbet [@woodPopulationSurfacesNew1991] used flexible spline models in population ecology modeling. Ellner et al. [@ellnerInferringMechanismTimeseries1997] described how to infer information about underlying or unobserved processes in a dynamical system using only time series data. Ellner et al. [@ellnerNoiseNonlinearityMeasles1998] introduced the concept of "semimechanistic" models, which combine deterministic specifications and parametric models for components supported by known biological mechanisms with non-parametric methods for flexible function estimation when insufficient information is available to justify a specific parametric form. Simon Wood [@woodPartiallySpecifiedEcological2024] presented a general methodology using penalized smoothing to estimate time-varying latent variables for dynamic ecological models through iterations of quasi-Newton methods with generalized cross-validation.

Implementing Wood's methodology requires expertise in statistical inference, non-linear optimization, splines, numerical analysis, and statistical computing, making it complex for many domain-specific modelers. Our goal was to develop a user-friendly way for modelers to estimate time-varying latent variables in non-stochastic compartmental models. We integrated Simon Wood's methodology for smoothing parameter estimation into the general-purpose compartmental modeling tool `macpan2`, which uses `TMB` for optimization. We use the `mgcv` package in R to obtain low-rank smoothing matrices for the basis and penalty, resulting in a software module within `macpan2` that allows users to easily formulate and fit semi-mechanistic models. 

Being able to quickly and easily estimate the transmission rate at each observation is crucial for infectious disease modelers. The transmission rate is integral to calculating other epidemiological quantities, such as the effective reproduction number (\(R_t\)), and provides the basis for many downstream applications, including evaluating intervention strategies, forecasting disease dynamics, identifying high-risk periods and populations, validating models, understanding transmission dynamics, assessing the impact of variants, and developing and testing hypotheses about factors influencing disease spread.

In Chapter \ref{Background}, we review the basic theory of univariate smoothing in the context of Gaussian regression and fitting compartmental models to data. We discuss the construction of linear smoothers, review different bases available in the R package `mgcv`, explore general penalized likelihood methods, and examine the relationship between smooths and random effects, including a Bayesian perspective. Chapter \ref{Materials-and-methods} covers the technical details required to implement the smoothing parameter estimation methodology in `macpan2`. Chapter \ref{Results} presents the results of the simulation study and applications to Scarlet Fever, COVID-19, and Measles datasets. Finally, Chapter \ref{Discussion} discusses the results, the assumptions and simplifications used in our modeling methodology, and future research avenues.

